name: Bug Report
description: Report an issue with Nutrition AI
labels: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the issue you encountered. Duplicate issues will be closed. [Issue Tracker](https://github.com/Passiolife/Nutrition-AI-Support/issues)
    options:
    - label: I have searched the tracker for existing similar issues and I know that duplicates will be closed
      required: true
- type: textarea
  attributes:
    label: Describe the Issue
    description: |
      A high-level summary or description of the problem that you're facing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: A list of steps that can be followed to recreate the issue.
    placeholder: |
      1. Open a new request tab
      2. Select the Body tab
      3. Select the `raw` type 
      4. See error message...
  validations:
    required: true
- type: markdown
  attributes:
    value: '> **Tip**: You can attach images and recordings to textareas by dragging in the files. More visual examples will help us to understand the issue.'
- type: textarea
  attributes:
    label: Screenshots or Videos
    description: | 
      If you are reporting a UI based issue, please include screenshots or a short video to help visually explain the problem.
      Ensure that the screenshots/videos are full screen and do not contain any sensitive information such as API keys or Access Tokens. 
  validations:
    required: false
- type: dropdown
  attributes:
    label: Framework
    description: Which framework are you using?
    options:
      - API
      - iOS SDK
      - Android SDK
      - Flutter SDK
      - RN SDK
  validations:
    required: true
- type: input
  attributes:
    label: SDK Version
    description: Which version of the SDK are you using?
    placeholder: "10.12.0"
  validations:
    required: false
